.PONY: sam
sam:
	@echo "Creating virtual environment..."
	@conda env create --name sam --file sam.yml
	@echo "Virtual environment created."

.PONY: run
run:
	@echo "Running sam..."
	bash run.sh
	@echo "sam run."