.PONY: petals
petals:
	@echo "Creating virtual environment..."
	@conda env create --name petals --file petals.yml
	@echo "Virtual environment created."

.PONY: run
run:
	@echo "Running petals..."
	bash run.sh
	@echo "petals run."