.PHONY: check
check:
	@echo "Checking..."
	@cargo check

.PHONY: build
build:
	@echo "Building..."
	@cargo build

.PHONY: run
run:
	@echo "Running..."
	@cargo run --release

.PHONY: doc
doc:
	@echo "Documenting..."
	@cargo doc --no-deps --document-private-items --open
