.PONY: outlines
outlines:
	@echo "Creating virtual environment..."
	@conda env create --name outlines --file outlines.yml
	@echo "Virtual environment created."

.PONY: run
run:
	@echo "Running outlines..."
	bash run.sh
	@echo "outlines run."
