.PHONY: check
check:
	@echo "Checking..."
	@cargo check

.PHONY: fmt
fmt:
	@echo "Formatting code..."
	@cargo fmt

.PHONY: build
build:
	@echo "Building..."
	@cargo build

.PHONY: doc
doc:
	@echo "Documenting..."
	@cargo doc --no-deps --document-private-items --open
