package nodes

import (
	"context"
	"os"
	"path/filepath"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	pb "github.com/mudler/LocalAI/pkg/grpc/proto"
)

// The receiving side writes a "<file>.sha256" sidecar next to every file it
// accepts (see file_transfer_server.go). When the sender walks a model
// directory it must skip those sidecars: staging them makes the receiver write
// a sidecar for the sidecar, so each pass multiplies the tree
// (config.json -> config.json.sha256 -> config.json.sha256.sha256 -> ...) and
// grows disk without bound on both ends.
var _ = Describe("stageModelFiles hash sidecars", func() {
	var (
		stager  *fakeFileStager
		router  *SmartRouter
		node    *BackendNode
		tmp     string
		modelID = "sidecar-model"
	)

	BeforeEach(func() {
		stager = &fakeFileStager{}
		router = &SmartRouter{
			fileStager:     stager,
			stagingTracker: NewStagingTracker(),
		}
		node = &BackendNode{ID: "node-1", Name: "node-1", Address: "10.0.0.1:50051"}
		tmp = GinkgoT().TempDir()
	})

	It("does not stage hash sidecars left behind by a previous transfer", func() {
		modelDir := filepath.Join(tmp, "models", modelID)
		Expect(os.MkdirAll(modelDir, 0o755)).To(Succeed())

		weights := filepath.Join(modelDir, "model.safetensors")
		config := filepath.Join(modelDir, "config.json")
		Expect(os.WriteFile(weights, []byte("weights"), 0o644)).To(Succeed())
		Expect(os.WriteFile(config, []byte("{}"), 0o644)).To(Succeed())

		// Sidecars a previous staging round deposited, including the chained
		// ones produced by the runaway this guards against.
		for _, sidecar := range []string{
			"model.safetensors.sha256",
			"config.json.sha256",
			"config.json.sha256.sha256",
			"config.json.sha256.sha256.sha256",
			"config.json.sha256.target",
		} {
			Expect(os.WriteFile(filepath.Join(modelDir, sidecar), []byte("deadbeef"), 0o644)).To(Succeed())
		}

		opts := &pb.ModelOptions{Model: modelID, ModelFile: modelDir}

		_, err := router.stageModelFiles(context.Background(), node, opts, "track-key")
		Expect(err).ToNot(HaveOccurred())

		staged := make([]string, 0, len(stager.ensureCalls))
		for _, c := range stager.ensureCalls {
			staged = append(staged, c.localPath)
		}
		Expect(staged).To(ConsistOf(weights, config),
			"only real model files may be staged; hash sidecars are regenerated by the receiver")
	})

	It("excludes hash sidecars from the staging file count", func() {
		modelDir := filepath.Join(tmp, "models", "counted")
		Expect(os.MkdirAll(modelDir, 0o755)).To(Succeed())
		Expect(os.WriteFile(filepath.Join(modelDir, "a.gguf"), []byte("a"), 0o644)).To(Succeed())
		Expect(os.WriteFile(filepath.Join(modelDir, "b.gguf"), []byte("b"), 0o644)).To(Succeed())
		for _, sidecar := range []string{"a.gguf.sha256", "b.gguf.sha256", "b.gguf.sha256.sha256"} {
			Expect(os.WriteFile(filepath.Join(modelDir, sidecar), []byte("x"), 0o644)).To(Succeed())
		}

		// The progress bar counts what will actually be uploaded; counting
		// sidecars strands it short of 100%.
		Expect(countStageableFiles(modelDir)).To(Equal(2))
	})

	It("still stages a model file whose own name ends in .sha256", func() {
		// Defensive: the skip must key off "sidecar sitting next to a real
		// file", not a blanket suffix ban, so a model that genuinely ships a
		// .sha256 payload with no base file is still transferred.
		modelDir := filepath.Join(tmp, "models", "checksums-only")
		Expect(os.MkdirAll(modelDir, 0o755)).To(Succeed())
		orphan := filepath.Join(modelDir, "manifest.sha256")
		Expect(os.WriteFile(orphan, []byte("abc"), 0o644)).To(Succeed())

		opts := &pb.ModelOptions{Model: "checksums-only", ModelFile: modelDir}

		_, err := router.stageModelFiles(context.Background(), node, opts, "track-key")
		Expect(err).ToNot(HaveOccurred())

		staged := make([]string, 0, len(stager.ensureCalls))
		for _, c := range stager.ensureCalls {
			staged = append(staged, c.localPath)
		}
		Expect(staged).To(ConsistOf(orphan))
	})
})
