.PONY: ttsvalle
ttsvalle:
	@echo "Creating virtual environment..."
	@conda env create --name ttsvalle --file ttsvalle.yml
	@echo "Virtual environment created."

.PONY: run
run:
	@echo "Running ttsvalle..."
	bash run.sh
	@echo "ttsvalle run."