.PHONY: diffusers
diffusers:
	@echo "Creating virtual environment..."
	@conda env create --name diffusers --file diffusers.yml
	@echo "Virtual environment created."

.PHONY: run
run:
	@echo "Running diffusers..."
	bash run.sh
	@echo "Diffusers run."
