.PHONY: ttsbark
ttsbark:
	$(MAKE) -C ../common-env/transformers

.PHONY: run
run:
	@echo "Running bark..."
	bash run.sh
	@echo "bark run."

.PHONY: test
test:
	@echo "Testing bark..."
	bash test.sh
	@echo "bark tested."
