FROM python

RUN apt-get update && apt-get -y install cmake

# convert the model (one-off)
RUN pip3 install torch numpy

WORKDIR /build
COPY ./scripts/ .

RUN git clone --recurse-submodules https://github.com/saharNooby/rwkv.cpp && cd rwkv.cpp && cmake . && cmake --build . --config Release
ENTRYPOINT [ "/build/build.sh" ]