.PHONY: transformers
transformers:
	$(MAKE) -C ../common-env/transformers

.PHONY: run
run:
	@echo "Running transformers..."
	bash run.sh
	@echo "transformers run."

# It is not working well by using command line. It only6 works with IDE like VSCode.
.PHONY: test
test:
	@echo "Testing transformers..."
	bash test.sh
	@echo "transformers tested."
